package com.sats.dna.icons

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.painterResource
import com.sats.dna.R

object SatsIcons {
    val add @Composable get() = painterResource(R.drawable.ic_add)
    val addPerson @Composable get() = painterResource(R.drawable.ic_add_person)
    val addToCalendar @Composable get() = painterResource(R.drawable.ic_add_to_calendar)
    val arrowDown @Composable get() = painterResource(R.drawable.ic_arrow_down)
    val arrowRight @Composable get() = painterResource(R.drawable.ic_arrow_right)
    val arrowUp @Composable get() = painterResource(R.drawable.ic_arrow_up)
    val back @Composable get() = painterResource(R.drawable.ic_back)
    val barbell @Composable get() = painterResource(R.drawable.ic_barbell)
    val calendar @Composable get() = painterResource(R.drawable.ic_calendar)
    val check @Composable get() = painterResource(R.drawable.ic_check)
    val checkRound @Composable get() = painterResource(R.drawable.ic_check_round)
    val checkSeal @Composable get() = painterResource(R.drawable.ic_check_seal)
    val checkThin @Composable get() = painterResource(R.drawable.ic_check_thin)

    @Deprecated("Replaced with arrowDown", ReplaceWith("arrowDown"))
    val chevronDown @Composable get() = arrowDown

    @Deprecated("Replaced with arrowRight", ReplaceWith("arrowRight"))
    val chevronRight @Composable get() = arrowRight

    @Deprecated("Replaced with arrowUp", ReplaceWith("arrowUp"))
    val chevronUp @Composable get() = arrowUp
    val clockFilled @Composable get() = painterResource(R.drawable.ic_clock_filled)
    val close @Composable get() = painterResource(R.drawable.ic_close)
    val comment @Composable get() = painterResource(R.drawable.ic_comment)
    val customerService @Composable get() = painterResource(R.drawable.ic_customer_service)
    val filter @Composable get() = painterResource(R.drawable.ic_filter)
    val findFriends @Composable get() = painterResource(R.drawable.ic_find_friends)
    val fistBump @Composable get() = painterResource(R.drawable.ic_fistbump)
    val fistBumpFilled @Composable get() = painterResource(R.drawable.ic_fistbump_filled)
    val flame @Composable get() = painterResource(R.drawable.ic_flame)
    val followersAndFollowees @Composable get() = painterResource(R.drawable.ic_followers_and_followees)
    val friends @Composable get() = painterResource(R.drawable.ic_friends)
    val gxClass @Composable get() = painterResource(R.drawable.ic_class)
    val hidden @Composable get() = painterResource(R.drawable.ic_hidden)
    val imagePlaceholder @Composable get() = painterResource(R.drawable.ic_image_placeholder)
    val images @Composable get() = painterResource(R.drawable.ic_images)
    val info @Composable get() = painterResource(R.drawable.ic_info)
    val join @Composable get() = painterResource(R.drawable.ic_join)
    val linkExternal @Composable get() = painterResource(R.drawable.ic_link_external)
    val location @Composable get() = painterResource(R.drawable.ic_location)
    val lock @Composable get() = painterResource(R.drawable.ic_lock)
    val logOut @Composable get() = painterResource(R.drawable.ic_log_out)
    val minus @Composable get() = painterResource(R.drawable.ic_minus)
    val moreVertical @Composable get() = painterResource(R.drawable.ic_more_vertical)
    val myPage @Composable get() = painterResource(R.drawable.ic_my_page)
    val navActivityFilled @Composable get() = painterResource(R.drawable.ic_nav_activity_filled)
    val navActivityOutlined @Composable get() = painterResource(R.drawable.ic_nav_activity_outlined)
    val navBookFilled @Composable get() = painterResource(R.drawable.ic_nav_book_filled)
    val navBookOutlined @Composable get() = painterResource(R.drawable.ic_nav_book_outlined)
    val navClubsFilled @Composable get() = painterResource(R.drawable.ic_nav_clubs_filled)
    val navClubsOutlined @Composable get() = painterResource(R.drawable.ic_nav_clubs_outlined)
    val navHomeElixiaFilled @Composable get() = painterResource(R.drawable.ic_nav_home_elixia_filled)
    val navHomeElixiaOutlined @Composable get() = painterResource(R.drawable.ic_nav_home_elixia_outlined)
    val navHomeSatsFilled @Composable get() = painterResource(R.drawable.ic_nav_home_sats_filled)
    val navHomeSatsOutlined @Composable get() = painterResource(R.drawable.ic_nav_home_sats_outlined)
    val navQrFilled @Composable get() = painterResource(R.drawable.ic_nav_qr_filled)
    val navQrOutlined @Composable get() = painterResource(R.drawable.ic_nav_qr_outlined)
    val negRemove @Composable get() = painterResource(R.drawable.ic_neg_remove)
    val privacyPolicy @Composable get() = painterResource(R.drawable.ic_privacy_policy)
    val profileOutlined @Composable get() = painterResource(R.drawable.ic_profile_outlined)
    val ptPackages @Composable get() = painterResource(R.drawable.ic_pt_packages)
    val qrCode @Composable get() = painterResource(R.drawable.ic_qr_code)
    val recruitFriends @Composable get() = painterResource(R.drawable.ic_recruit_friends)
    val rewardsElixia @Composable get() = painterResource(R.drawable.ic_rewards_elixia)
    val rewardsSats @Composable get() = painterResource(R.drawable.ic_rewards_sats)
    val search @Composable get() = painterResource(R.drawable.ic_search)
    val send @Composable get() = painterResource(R.drawable.ic_send)
    val settings @Composable get() = painterResource(R.drawable.ic_settings)
    val share @Composable get() = painterResource(R.drawable.ic_share)
    val showing @Composable get() = painterResource(R.drawable.ic_showing)
    val starFilled @Composable get() = painterResource(R.drawable.ic_star_filled)
    val starOutlined @Composable get() = painterResource(R.drawable.ic_star_outlined)
    val termsAndConditions @Composable get() = painterResource(R.drawable.ic_terms_and_conditions)
    val tick @Composable get() = painterResource(R.drawable.ic_tick)
    val time @Composable get() = painterResource(R.drawable.ic_time)
    val treatment @Composable get() = painterResource(R.drawable.ic_treatment)
    val trophy @Composable get() = painterResource(R.drawable.ic_trophy)
    val vouchersAndGiftCards @Composable get() = painterResource(R.drawable.ic_vouchers_and_gift_cards)
    val workoutCardio @Composable get() = painterResource(R.drawable.ic_workout_cardio)
    val workoutGx @Composable get() = painterResource(R.drawable.ic_workout_gx)
    val workoutGymFloor @Composable get() = painterResource(R.drawable.ic_workout_gym_floor)
    val workoutOther @Composable get() = painterResource(R.drawable.ic_workout_other)
    val workoutPlan @Composable get() = painterResource(R.drawable.ic_workout_plan)
    val workoutPt @Composable get() = painterResource(R.drawable.ic_workout_pt)
}
