package com.sats.dna.icons

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.painterResource
import com.sats.dna.R

object SatsIcons {
    val add @Composable get() = painterResource(R.drawable.ic_add)
    val addPerson @Composable get() = painterResource(R.drawable.ic_add_person)
    val addToCalendar @Composable get() = painterResource(R.drawable.ic_add_to_calendar)
    val arrowDown @Composable get() = painterResource(R.drawable.ic_arrow_down)
    val arrowRight @Composable get() = painterResource(R.drawable.ic_arrow_right)
    val arrowUp @Composable get() = painterResource(R.drawable.ic_arrow_up)
    val back @Composable get() = painterResource(R.drawable.ic_back)
    val barbell @Composable get() = painterResource(R.drawable.ic_barbell)
    val bellCherry @Composable get() = painterResource(R.drawable.ic_bell_cherry)
    val booked @Composable get() = painterResource(R.drawable.ic_booked)
    val calendar @Composable get() = painterResource(R.drawable.ic_calendar)
    val card @Composable get() = painterResource(R.drawable.ic_card)
    val cardio @Composable get() = painterResource(R.drawable.ic_cardio)
    val check @Composable get() = painterResource(R.drawable.ic_check)
    val checkSeal @Composable get() = painterResource(R.drawable.ic_check_seal)
    val cherry @Composable get() = painterResource(R.drawable.ic_cherry)
    val clockFilled @Composable get() = painterResource(R.drawable.ic_clock_filled)
    val close @Composable get() = painterResource(R.drawable.ic_close)
    val comment @Composable get() = painterResource(R.drawable.ic_comment)
    val confirm @Composable get() = painterResource(R.drawable.ic_confirm)
    val delete @Composable get() = painterResource(R.drawable.ic_delete)
    val edit @Composable get() = painterResource(R.drawable.ic_edit)
    val filter @Composable get() = painterResource(R.drawable.ic_filter)
    val fistBump @Composable get() = painterResource(R.drawable.ic_fist_bump)
    val fistBumpFilled @Composable get() = painterResource(R.drawable.ic_fist_bump_filled)
    val flame @Composable get() = painterResource(R.drawable.ic_flame)
    val friends @Composable get() = painterResource(R.drawable.ic_friends)
    val graph @Composable get() = painterResource(R.drawable.ic_graph)
    val gxClass @Composable get() = painterResource(R.drawable.ic_gx_class)
    val hidden @Composable get() = painterResource(R.drawable.ic_hidden)
    val imagePlaceholder @Composable get() = painterResource(R.drawable.ic_image_placeholder)
    val images @Composable get() = painterResource(R.drawable.ic_images)
    val info @Composable get() = painterResource(R.drawable.ic_info)
    val join @Composable get() = painterResource(R.drawable.ic_join)
    val linkExternal @Composable get() = painterResource(R.drawable.ic_link_external)
    val location @Composable get() = painterResource(R.drawable.ic_location)
    val lock @Composable get() = painterResource(R.drawable.ic_lock)
    val minus @Composable get() = painterResource(R.drawable.ic_minus)
    val moreVertical @Composable get() = painterResource(R.drawable.ic_more_vertical)
    val myPtPackages @Composable get() = painterResource(R.drawable.ic_my_pt_packages)
    val navActivityFilled @Composable get() = painterResource(R.drawable.ic_nav_activity_filled)
    val navActivityOutlined @Composable get() = painterResource(R.drawable.ic_nav_activity_outlined)
    val navBookFilled @Composable get() = painterResource(R.drawable.ic_nav_book_filled)
    val navBookOutlined @Composable get() = painterResource(R.drawable.ic_nav_book_outlined)
    val navClubsFilled @Composable get() = painterResource(R.drawable.ic_nav_clubs_filled)
    val navClubsOutlined @Composable get() = painterResource(R.drawable.ic_nav_clubs_outlined)
    val navHomeElixiaFilled @Composable get() = painterResource(R.drawable.ic_nav_home_elixia_filled)
    val navHomeElixiaOutlined @Composable get() = painterResource(R.drawable.ic_nav_home_elixia_outlined)
    val navHomeSatsFilled @Composable get() = painterResource(R.drawable.ic_nav_home_sats_filled)
    val navHomeSatsOutlined @Composable get() = painterResource(R.drawable.ic_nav_home_sats_outlined)
    val navQrFilled @Composable get() = painterResource(R.drawable.ic_nav_qr_filled)
    val navQrOutlined @Composable get() = painterResource(R.drawable.ic_nav_qr_outlined)
    val negRemove @Composable get() = painterResource(R.drawable.ic_neg_remove)
    val notifications @Composable get() = painterResource(R.drawable.ic_notifications)
    val personalTrainer @Composable get() = painterResource(R.drawable.ic_pt)
    val play @Composable get() = painterResource(R.drawable.ic_play)
    val privacy @Composable get() = painterResource(R.drawable.ic_privacy)
    val privacyPolicy @Composable get() = painterResource(R.drawable.ic_privacy_policy)
    val profile @Composable get() = painterResource(R.drawable.ic_profile)
    val qr @Composable get() = painterResource(R.drawable.ic_qr)
    val questionMark @Composable get() = painterResource(R.drawable.ic_question_mark)
    val refresh @Composable get() = painterResource(R.drawable.ic_refresh)
    val remove @Composable get() = painterResource(R.drawable.ic_remove)
    val rewardsElixia @Composable get() = painterResource(R.drawable.ic_rewards_elixia)
    val rewardsSats @Composable get() = painterResource(R.drawable.ic_rewards_sats)
    val search @Composable get() = painterResource(R.drawable.ic_search)
    val send @Composable get() = painterResource(R.drawable.ic_send)
    val settings @Composable get() = painterResource(R.drawable.ic_settings)
    val share @Composable get() = painterResource(R.drawable.ic_share)
    val showing @Composable get() = painterResource(R.drawable.ic_showing)
    val star @Composable get() = painterResource(R.drawable.ic_star)
    val starBorder @Composable get() = painterResource(R.drawable.ic_star_border)
    val time @Composable get() = painterResource(R.drawable.ic_time)
    val treatments @Composable get() = painterResource(R.drawable.ic_treatments)
    val trophy @Composable get() = painterResource(R.drawable.ic_trophy)
    val vouchers @Composable get() = painterResource(R.drawable.ic_vouchers)
    val warningSign @Composable get() = painterResource(R.drawable.ic_warning_sign)
    val workoutGx @Composable get() = painterResource(R.drawable.ic_workout_gx)
    val workoutGymFloor @Composable get() = painterResource(R.drawable.ic_workout_gym_floor)
    val workoutOther @Composable get() = painterResource(R.drawable.ic_workout_other)
    val workoutPlan @Composable get() = painterResource(R.drawable.ic_workout_plan)
    val workoutPt @Composable get() = painterResource(R.drawable.ic_workout_pt)
}

@Composable
fun SatsIcons.fistBump(isLiked: Boolean) = if (isLiked) fistBumpFilled else fistBump
