package com.sats.dna.icons

import androidx.compose.material.Icon
import androidx.compose.material.icons.materialIcon
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import com.sats.dna.SatsIcons

@Suppress("UnusedReceiverParameter") // for convenient access
val SatsIcons.Trophy: ImageVector
    get() {
        if (_trophy != null) {
            return _trophy!!
        }

        _trophy = materialIcon(name = "Trophy") {
            path(
                fill = SolidColor(Color.Black),
            ) {
                moveTo(4f, 7.1f)
                horizontalLineTo(3.25f)
                horizontalLineTo(4f)
                close()
                moveToRelative(16f, 0f)
                horizontalLineToRelative(0.75f)
                horizontalLineTo(20f)
                close()
                moveTo(16.8f, 21f)
                verticalLineToRelative(0.75f)
                curveToRelative(0.41f, 0f, 0.75f, -0.34f, 0.75f, -0.75f)
                horizontalLineTo(16.8f)
                close()
                moveToRelative(-9.6f, 0f)
                horizontalLineTo(6.45f)
                curveToRelative(0f, 0.41f, 0.34f, 0.75f, 0.75f, 0.75f)
                verticalLineTo(21f)
                close()
                moveToRelative(3.2f, -3.27f)
                verticalLineToRelative(0.75f)
                verticalLineToRelative(-0.75f)
                close()
                moveTo(7.2f, 8.8f)
                horizontalLineTo(6.4f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(0.8f)
                verticalLineTo(8.8f)
                close()
                moveToRelative(-0.8f, 0f)
                curveToRelative(-0.43f, 0f, -0.85f, -0.18f, -1.16f, -0.5f)
                lineTo(4.17f, 9.35f)
                curveToRelative(0.59f, 0.6f, 1.39f, 0.95f, 2.23f, 0.95f)
                verticalLineTo(8.8f)
                close()
                moveTo(5.24f, 8.3f)
                curveTo(4.93f, 7.98f, 4.75f, 7.55f, 4.75f, 7.1f)
                horizontalLineToRelative(-1.5f)
                curveToRelative(0f, 0.84f, 0.33f, 1.65f, 0.92f, 2.25f)
                lineTo(5.24f, 8.3f)
                close()
                moveTo(4.75f, 7.1f)
                verticalLineTo(4f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(3.1f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(5f, 3.74f)
                horizontalLineToRelative(2.2f)
                verticalLineToRelative(-1.5f)
                horizontalLineTo(5f)
                verticalLineToRelative(1.5f)
                close()
                moveTo(4.75f, 4f)
                curveToRelative(0f, -0.14f, 0.11f, -0.25f, 0.25f, -0.25f)
                verticalLineToRelative(-1.5f)
                curveTo(4.03f, 2.25f, 3.25f, 3.03f, 3.25f, 4f)
                horizontalLineToRelative(1.5f)
                close()
                moveToRelative(12.05f, 6.3f)
                horizontalLineToRelative(0.8f)
                verticalLineTo(8.8f)
                horizontalLineToRelative(-0.8f)
                verticalLineToRelative(1.5f)
                close()
                moveToRelative(0.8f, 0f)
                curveToRelative(0.84f, 0f, 1.64f, -0.35f, 2.23f, -0.95f)
                lineTo(18.76f, 8.3f)
                curveToRelative(-0.31f, 0.32f, -0.73f, 0.5f, -1.16f, 0.5f)
                verticalLineToRelative(1.5f)
                close()
                moveToRelative(2.23f, -0.95f)
                curveToRelative(0.6f, -0.6f, 0.92f, -1.41f, 0.92f, -2.26f)
                horizontalLineToRelative(-1.5f)
                curveToRelative(0f, 0.46f, -0.18f, 0.9f, -0.49f, 1.21f)
                lineToRelative(1.07f, 1.05f)
                close()
                moveToRelative(0.92f, -2.26f)
                verticalLineTo(4f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(3.1f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(19f, 2.25f)
                horizontalLineToRelative(-2.2f)
                verticalLineToRelative(1.5f)
                horizontalLineTo(19f)
                verticalLineToRelative(-1.5f)
                close()
                moveTo(20.75f, 4f)
                curveToRelative(0f, -0.97f, -0.78f, -1.75f, -1.75f, -1.75f)
                verticalLineToRelative(1.5f)
                curveToRelative(0.14f, 0f, 0.25f, 0.11f, 0.25f, 0.25f)
                horizontalLineToRelative(1.5f)
                close()
                moveToRelative(-8f, 13.73f)
                verticalLineToRelative(-3.28f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(3.28f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(12f, 13.7f)
                curveToRelative(-1.07f, 0f, -2.1f, -0.43f, -2.86f, -1.2f)
                lineToRelative(-1.07f, 1.04f)
                curveTo(9.11f, 14.6f, 10.52f, 15.2f, 12f, 15.2f)
                verticalLineToRelative(-1.5f)
                close()
                moveToRelative(-2.86f, -1.2f)
                curveToRelative(-0.76f, -0.79f, -1.19f, -1.85f, -1.19f, -2.95f)
                horizontalLineToRelative(-1.5f)
                curveToRelative(0f, 1.5f, 0.58f, 2.93f, 1.62f, 4f)
                lineToRelative(1.07f, -1.06f)
                close()
                moveTo(7.95f, 9.54f)
                verticalLineTo(3f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(6.55f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(7.2f, 3.75f)
                horizontalLineToRelative(9.6f)
                verticalLineToRelative(-1.5f)
                horizontalLineTo(7.2f)
                verticalLineToRelative(1.5f)
                close()
                moveTo(16.05f, 3f)
                verticalLineToRelative(6.55f)
                horizontalLineToRelative(1.5f)
                verticalLineTo(3f)
                horizontalLineToRelative(-1.5f)
                close()
                moveToRelative(0f, 6.55f)
                curveToRelative(0f, 1.1f, -0.43f, 2.16f, -1.2f, 2.94f)
                lineToRelative(1.08f, 1.05f)
                curveToRelative(1.04f, -1.06f, 1.62f, -2.5f, 1.62f, -4f)
                horizontalLineToRelative(-1.5f)
                close()
                moveToRelative(-1.2f, 2.94f)
                curveTo(14.1f, 13.27f, 13.08f, 13.7f, 12f, 13.7f)
                verticalLineToRelative(1.5f)
                curveToRelative(1.48f, 0f, 2.9f, -0.6f, 3.93f, -1.66f)
                lineToRelative(-1.07f, -1.05f)
                close()
                moveToRelative(1.95f, 7.76f)
                horizontalLineTo(7.2f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(9.6f)
                verticalLineToRelative(-1.5f)
                close()
                moveTo(7.95f, 21f)
                curveToRelative(0f, -0.67f, 0.26f, -1.32f, 0.72f, -1.79f)
                lineTo(7.6f, 18.16f)
                curveTo(6.86f, 18.92f, 6.45f, 19.94f, 6.45f, 21f)
                horizontalLineToRelative(1.5f)
                close()
                moveToRelative(0.72f, -1.79f)
                curveToRelative(0.46f, -0.47f, 1.09f, -0.73f, 1.73f, -0.73f)
                verticalLineToRelative(-1.5f)
                curveToRelative(-1.05f, 0f, -2.06f, 0.43f, -2.8f, 1.18f)
                lineToRelative(1.07f, 1.05f)
                close()
                moveToRelative(1.73f, -0.73f)
                horizontalLineToRelative(3.2f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.2f)
                verticalLineToRelative(1.5f)
                close()
                moveToRelative(3.2f, 0f)
                curveToRelative(0.64f, 0f, 1.27f, 0.26f, 1.73f, 0.73f)
                lineToRelative(1.07f, -1.05f)
                curveToRelative(-0.74f, -0.75f, -1.75f, -1.18f, -2.8f, -1.18f)
                verticalLineToRelative(1.5f)
                close()
                moveToRelative(1.73f, 0.73f)
                curveToRelative(0.46f, 0.47f, 0.72f, 1.12f, 0.72f, 1.79f)
                horizontalLineToRelative(1.5f)
                curveToRelative(0f, -1.06f, -0.41f, -2.08f, -1.15f, -2.84f)
                lineToRelative(-1.07f, 1.05f)
                close()
            }
        }

        return _trophy!!
    }

@Suppress("ObjectPropertyName")
private var _trophy: ImageVector? = null

@Preview
@Composable
private fun SatsIconTrophyPreview() {
    Icon(SatsIcons.Trophy, contentDescription = null)
}
