name: CI Checks

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  lint-kotlin:
    if: github.event.pull_request.draft == false
    name: Lint Kotlin
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Lint Kotlin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlin
