name: Build and release

on:
  push:
    tags:
      - v*.*.*

jobs:
  run-tests:
    name: Run Tests
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  build-lib:
    name: Build Library
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: run-tests
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Generate Version Name
        run: echo "VERSION_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_ENV

      - name: Decode Keystore File
        run: echo $KEYSTORE_FILE_BASE64 | base64 --decode - > $GITHUB_WORKSPACE/play-upload.keystore
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.PLAY_UPLOAD_KEYSTORE_FILE_BASE64 }}

      - name: Build library
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :sats-dna:build
        env:
          SATS_KEYSTORE_FILE: ${{ github.workspace }}/play-upload.keystore
          SATS_KEYSTORE_PASSWORD: ${{ secrets.PLAY_UPLOAD_KEYSTORE_PASSWORD }}
          SATS_KEYSTORE_KEY_ALIAS: ${{ secrets.PLAY_UPLOAD_KEY_ALIAS }}
          SATS_KEYSTORE_KEY_PASSWORD: ${{ secrets.PLAY_UPLOAD_KEY_PASSWORD }}

      - name: Remove Decoded Keystore File
        run: rm $GITHUB_WORKSPACE/play-upload.keystore

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sats-dna-lib
          path: sats-dna/build/outputs/aar/sats-dna-release.aar
          if-no-files-found: error

  release-lib:
    name: Release Library
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: build-lib
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Generate Version Name
        run: echo "VERSION_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: sats-dna-lib
          path: sats-dna/build/outputs/aar/

      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :sats-dna:publishReleasePublicationToGitHubPackagesRepository
        env:
          GH_PACKAGES_USERNAME: ${{ secrets.GH_PACKAGES_USERNAME }}
          GH_PACKAGES_PASSWORD: ${{ secrets.GH_PACKAGES_PASSWORD }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: sats-dna/build/outputs/aar/sats-dna-release.aar
          artifactErrorsFailBuild: true
          makeLatest: true

  build-sample-app:
    name: Build DNA Sample App
    needs: run-tests
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Generate Version Code
        run: echo "VERSION_CODE=$((2 + $GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: Generate Version Name
        run: echo "VERSION_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_ENV

      - name: Decode Keystore File
        run: echo $KEYSTORE_FILE_BASE64 | base64 --decode - > $GITHUB_WORKSPACE/play-upload.keystore
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.PLAY_UPLOAD_KEYSTORE_FILE_BASE64 }}

      - name: Generate App Bundle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :sample-app:bundleRelease
        env:
          SATS_KEYSTORE_FILE: ${{ github.workspace }}/play-upload.keystore
          SATS_KEYSTORE_PASSWORD: ${{ secrets.PLAY_UPLOAD_KEYSTORE_PASSWORD }}
          SATS_KEYSTORE_KEY_ALIAS: ${{ secrets.PLAY_UPLOAD_KEY_ALIAS }}
          SATS_KEYSTORE_KEY_PASSWORD: ${{ secrets.PLAY_UPLOAD_KEY_PASSWORD }}

      - name: Remove Decoded Keystore File
        run: rm $GITHUB_WORKSPACE/play-upload.keystore

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sats-dna-sample-app
          path: sample-app/build/outputs/bundle/release/sample-app-release.aab
          if-no-files-found: error

  release-sample-app:
    name: Release DNA Sample App
    needs: build-sample-app
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 5

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: sats-dna-sample-app
          path: sample-app/build/outputs/bundle/release/

      - name: Upload Bundle to Play Store
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          releaseFiles: sample-app/build/outputs/bundle/release/sample-app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.sats.dna.sample
          track: beta
          inAppUpdatePriority: 5
